language: c
compiler:
    - gcc
    - clang
script:
    - export CC="$CC" TEST_PREFIX="`pwd`/test_prefix"
    - make CC="$CC" PREFIX="${TEST_PREFIX}"
    - make CC="$CC" PREFIX="${TEST_PREFIX}" install
    - tree ${TEST_PREFIX}
    - ${TEST_PREFIX}/bin/clbiff --version
    - ${TEST_PREFIX}/bin/clbiff --help
    - ${TEST_PREFIX}/bin/clbiff -f . -i 1 -c date -v &
    - ./test.sh
    - kill %${TEST_PREFIX}/bin/clbiff
    - make clean
    - rm -rf ${TEST_PREFIX}
    - unset TEST_PREFIX
 
